site_name: nitorch-interpol
site_url: https://nitorch-interpol.readthedocs.io
repo_url: https://github.com/nitorch/nitorch-interpol
edit_uri: blob/main/docs/md
site_dir: html
docs_dir: md
theme: 
  name: material
plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [..]
        options:
          docstring_style: numpy
          merge_init_into_class: True
          separate_signature: True
          members_order: source
          show_source: False
          show_root_heading: True
          preload_modules: 
          - jitfields
markdown_extensions:
- pymdownx.arithmatex:
    generic: true
extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
- Home: index.md
- Installation: install.md
- Getting Started: start.md
- API: 
  - pushpull: api/pushpull.md
  - grids: api/grids.md
  - multires: api/multires.md
  - splines: api/splines.md
  - types: api/typing.md

watch:
- ../nitorch_interpol

